# Header
navname: AI

# navigatior items
nav:
  联系我们: https://o.n2book.com
  文档: /archives
  版本: /version
  
# favicon
favicon: /favicon.ico

# Profile
nickname: AIGC

### this variable is MarkDown form.
description: 文字、图片、视频 个人AI应用 <br>  [**立即开始**](https://o.n2book.com)<br> 
avatar: /image/logo.png

# main menu navigation
## links key words should not be changed.
## Complete url after key words.
## Unused key can be commented out.
links:
  Blog: /archives
  # Category:
  # Tags: 
  Link: https://chatbot.weixin.qq.com/webapp/zFmi6PogYXH8ddvqILtS68l8Z4KbVL?robotName=AI
  # Resume:
  # Publish:
  # Trophy:
  # Gallery:
  # RSS:
  # AliPay:
  # ZhiHu: https://www.zhihu.com/people/onsoul
  # LinkedIn:
  # FaceBook:
  # Twitter:
  # Skype:
  #CodeSandBox:
  #CodePen:
  # Sketch:
  # Gitlab:
  # Dribbble:
  # Instagram:
  # Reddit:
  # YouTube:
  # QQ:
  # Weibo:
  WeChat: https://chatbot.weixin.qq.com/webapp/zFmi6PogYXH8ddvqILtS68l8Z4KbVL?robotName=AI
  Github: https://chatbot.weixin.qq.com/webapp/zFmi6PogYXH8ddvqILtS68l8Z4KbVL?robotName=AI

# how links show: you have 2 choice--text or icon.
links_text_enable: false
links_icon_enable: true

# Post page
## Post_meta
post_meta_enable: true

post_author_enable: true
post_date_enable: true
post_category_enable: true
## Post copyright
post_copyright_enable: true

post_copyright_author_enable: true
post_copyright_permalink_enable: true
post_copyright_license_enable: false
post_copyright_license_text: 相关问题可问 <a href="https://chatbot.weixin.qq.com/webapp/zFmi6PogYXH8ddvqILtS68l8Z4KbVL?robotName=AI">留言</a>
post_copyright_slogan_enable: true
post_copyright_slogan_text: 更多问题 <a href="https://chatbot.weixin.qq.com/webapp/zFmi6PogYXH8ddvqILtS68l8Z4KbVL?robotName=AI">留言反馈</a>
## toc
post_toc_enable: true

# Page
page_title_enable: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM D, YYYY
time_format: H:mm:ss

# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

# scripts loaded in the end of the body
scripts:
  - /js/script.js
  - /js/tocbot.min.js
    # tscanlin/tocbot: Build a table of contents from headings in an HTML document.
    # https://github.com/tscanlin/tocbot


# plugin functions
## Mathjax: Math Formula Support
## https://www.mathjax.org
mathjax:
  enable: true
  import: demand # global or demand
  ## global: all pages will load mathjax,this will degrade performance and some grammers may be parsed wrong.
  ## demand: Recommend option,if your post need fomula, you can declare 'mathjax: true' in Front-matter
